# ----------------------
# Stage 1: Build go-librespot
# ----------------------
FROM golang:1.26-alpine AS builder

RUN apk add --no-cache \
    git \
    build-base \
    pkgconf \
    alsa-lib-dev \
    libogg-dev \
    libvorbis-dev \
    flac-dev

RUN git clone --branch dj-clean-clip-fix https://github.com/plisker/go-librespot.git /go-librespot
WORKDIR /go-librespot
RUN go mod download
RUN go build -v -o /daemon ./cmd/daemon

# ----------------------
# Stage 2: Runtime image
# ----------------------
FROM alpine:3.23

RUN apk add --no-cache \
    bash \
    ca-certificates \
    avahi \
    libgcc \
    gcompat \
    alsa-lib \
    libogg \
    libvorbis \
    flac

ENV PULSE_SERVER=tcp:localhost:4317

COPY --from=builder /daemon /usr/src/daemon
COPY start.sh /usr/src/

WORKDIR /usr/src/
CMD ["/bin/bash", "/usr/src/start.sh"]
